### ISSUE TITLE
Change Struct/Port YAML to move "ethernet" section back up a level.

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/oftr#5]
The expectation is that the port_desc['curr_speed'] will give the port's speed. The current schema requires it to be accessed as port_desc['ethernet']['curr_speed'].

```
Struct/Port: 
  port_no: PortNumber
  hw_addr: MacAddress
  name: Str16
  config: [PortConfigFlags]
  state: [PortStateFlags]
  ethernet:
    curr: [PortFeaturesFlags]
    advertised: [PortFeaturesFlags]
    supported: [PortFeaturesFlags]
    peer: [PortFeaturesFlags]
    curr_speed: UInt32
    max_speed: UInt32
  optical: !optout
    supported: [OpticalPortFeaturesFlags]
    tx_min_freq_lmda: UInt32
    tx_max_freq_lmda: UInt32
    tx_grid_freq_lmda: UInt32
    rx_min_freq_lmda: UInt32
    rx_max_freq_lmda: UInt32
    rx_grid_freq_lmda: UInt32
    tx_pwr_min: UInt16
    tx_pwr_max: UInt16
  properties: !opt [ExperimenterProperty]
```
