### ISSUE TITLE
Fixup: ANY vs ALL in Request.Port_Stats and elsewhere?

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/oftr#6]
Add a fixup for ANY vs ALL?  

Example that works:

```yaml
type: REQUEST.PORT_STATS
msg:
  port_no: ANY
```

Example the doesn't do what you expect:

```yaml
type: REQUEST.PORT_STATS
msg:
  port_no: ALL
```
